package cli

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/DiLRandI/OTelPlan/internal/backend/otelc"
	"github.com/DiLRandI/OTelPlan/internal/discovery"
	"github.com/DiLRandI/OTelPlan/internal/policy"
	"github.com/DiLRandI/OTelPlan/internal/resolve"
	"github.com/DiLRandI/OTelPlan/internal/suggest"
	"github.com/DiLRandI/OTelPlan/internal/validate"
	"github.com/DiLRandI/OTelPlan/pkg/model"
	"gopkg.in/yaml.v3"
)

const (
	maxStarterRules = 20
	minStarterScore = 3
	starterFileMode = 0o600
	exitAnalysis    = 4
	exitValidation  = 5
	exitBackend     = 7
	starterHeader   = "# Generated by otelplan init. Review exact-symbol suggestions before committing.\n" +
		"# Scores are advisory. No arguments or results are captured by default.\n"
)

var (
	errEmptyStarterPath     = errors.New("init output path must not be empty")
	errStarterExtension     = errors.New("init output must be a .yaml or .yml policy file")
	errStarterNotRegular    = errors.New("starter policy destination must be a regular file")
	errStarterAlreadyExists = errors.New("starter policy already exists; use --force to replace it")
)

type initSummary struct {
	Path        string               `json:"path"`
	Suggestions []suggest.Suggestion `json:"suggestions"`
}

func initCommand(ctx context.Context, opts options, patterns []string) (any, int, model.DiagnosticErrorList) {
	fail := func(exit int, code model.Code, message string) (any, int, model.DiagnosticErrorList) {
		diagnostic := new(model.DiagnosticError)
		diagnostic.Severity, diagnostic.Code, diagnostic.Message = model.SeverityError, code, message

		return nil, exit, model.DiagnosticErrorList{*diagnostic}
	}

	path, err := starterPolicyPath(opts)
	if err != nil {
		return fail(exitUsage, model.CodeInvalidPolicy, err.Error())
	}

	err = checkStarterDestination(path, opts.force)
	if err != nil {
		return fail(1, model.CodeArtifactOutput, err.Error())
	}

	patterns = normalizedStarterPatterns(patterns)
	analysis := new(discovery.Options)
	analysis.Root, analysis.Patterns = opts.root, patterns
	analysis.CallGraph, analysis.Offline = true, opts.offline

	code, err := discovery.LoadContext(ctx, *analysis)
	if err != nil {
		return fail(exitAnalysis, model.CodeUnresolvedSymbol, fmt.Sprintf("analyze project for starter policy: %v", err))
	}

	starter, selected := starterPolicy(code, patterns)
	if len(selected) == 0 {
		return fail(exitValidation, model.CodeUnresolvedSymbol,
			"no safe starter candidates have enough evidence; inspect symbols and write an explicit policy")
	}

	diagnostics, exit := validateStarterPolicy(starter, code, len(selected))
	if exit != 0 {
		return nil, exit, diagnostics
	}

	data, err := yaml.Marshal(starter)
	if err != nil {
		return fail(1, model.CodeArtifactOutput, fmt.Sprintf("encode starter policy: %v", err))
	}

	data = append([]byte(starterHeader), data...)

	err = writeStarterPolicy(path, data, opts.force)
	if err != nil {
		return fail(1, model.CodeArtifactOutput, err.Error())
	}

	return initSummary{Path: path, Suggestions: selected}, 0, diagnostics
}

func validateStarterPolicy(starter *model.Policy, code *model.CodeModel,
	expected int,
) (model.DiagnosticErrorList, int) {
	diagnostics := policy.Validate(starter)
	if diagnostics.HasErrors() {
		return diagnostics, exitValidation
	}

	result := resolve.Resolve(starter, code)
	diagnostics = append(diagnostics, result.Diagnostics...)

	var safetyOptions validate.Options

	diagnostics = append(diagnostics, validate.Safety(code, result.Plan, safetyOptions)...)
	if diagnostics.HasErrors() || len(result.Plan.Targets) != expected {
		diagnostic := new(model.DiagnosticError)
		diagnostic.Severity, diagnostic.Code = model.SeverityError, model.CodeInvalidPolicy
		diagnostic.Message = "starter suggestions did not resolve to exact valid targets"

		return append(diagnostics, *diagnostic), exitValidation
	}

	backendDiagnostics := otelc.Check(starter.Backend.Version, code, result.Plan)
	if backendDiagnostics.HasErrors() {
		return append(diagnostics, backendDiagnostics...), exitBackend
	}

	return append(diagnostics, backendDiagnostics...), 0
}

func normalizedStarterPatterns(patterns []string) []string {
	if len(patterns) == 0 {
		return []string{"./..."}
	}

	result := append([]string(nil), patterns...)
	slices.Sort(result)

	return slices.Compact(result)
}

func starterPolicy(code *model.CodeModel, patterns []string) (*model.Policy, []suggest.Suggestion) {
	starter := new(model.Policy)
	starter.APIVersion, starter.Kind = model.APIVersionV1Alpha1, model.KindInstrumentationPlan

	starter.Project.Packages = append([]string(nil), patterns...)
	starter.Project.BuildTags = append([]string(nil), code.EffectiveBuild.BuildTags...)
	starter.Backend.Name, starter.Backend.Version = model.BackendNameOTelC, otelc.SupportedVersion
	starter.Defaults.Context.Mode = model.ContextModeRequire
	starter.Defaults.Errors.Record = true

	selected := make([]suggest.Suggestion, 0, maxStarterRules)
	for _, candidate := range suggest.Rank(code) {
		if candidate.Score < minStarterScore || len(selected) == maxStarterRules {
			break
		}

		match := new(model.Match)
		match.Symbols = []string{string(candidate.SymbolID)}
		rule := new(model.Rule)
		rule.ID = starterRuleID(candidate.SymbolID)
		rule.Description = fmt.Sprintf("Suggestion (%s confidence, score %d): %s",
			candidate.Confidence, candidate.Score, strings.Join(candidate.Evidence, "; "))
		rule.Match = *match
		starter.Rules = append(starter.Rules, *rule)
		selected = append(selected, candidate)
	}

	return starter, selected
}

func starterRuleID(symbol model.SymbolID) string {
	digest := sha256.Sum256([]byte(symbol))

	return "suggest-" + hex.EncodeToString(digest[:6])
}

func starterPolicyPath(opts options) (string, error) {
	name := "otelplan.yaml"
	if opts.outputSet {
		name = opts.output
	}

	if name == "" {
		return "", errEmptyStarterPath
	}

	if extension := filepath.Ext(name); extension != ".yaml" && extension != ".yml" {
		return "", errStarterExtension
	}

	if !filepath.IsAbs(name) {
		name = filepath.Join(opts.root, name)
	}

	path, err := filepath.Abs(name)
	if err != nil {
		return "", fmt.Errorf("resolve starter policy output: %w", err)
	}

	return path, nil
}

func checkStarterDestination(path string, force bool) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}

	if err != nil {
		return fmt.Errorf("inspect starter policy destination: %w", err)
	}

	if !info.Mode().IsRegular() {
		return errStarterNotRegular
	}

	if !force {
		return errStarterAlreadyExists
	}

	return nil
}

func writeStarterPolicy(path string, data []byte, force bool) error {
	root, err := os.OpenRoot(filepath.Dir(path))
	if err != nil {
		return fmt.Errorf("open starter policy output directory: %w", err)
	}
	defer func() { _ = root.Close() }()

	name := filepath.Base(path)
	if !force {
		return writeNewStarterPolicy(root, name, data)
	}

	return replaceStarterPolicy(root, name, data)
}

func writeNewStarterPolicy(root *os.Root, name string, data []byte) error {
	file, err := root.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_EXCL, starterFileMode)
	if err != nil {
		return fmt.Errorf("create starter policy: %w", err)
	}

	complete := false
	defer func() {
		if !complete {
			_ = root.Remove(name)
		}
	}()

	_, err = file.Write(data)
	if err != nil {
		_ = file.Close()

		return fmt.Errorf("write starter policy: %w", err)
	}

	err = file.Close()
	if err != nil {
		return fmt.Errorf("close starter policy: %w", err)
	}

	complete = true

	return nil
}

func replaceStarterPolicy(root *os.Root, name string, data []byte) error {
	file, err := os.CreateTemp(root.Name(), ".otelplan-init-*.tmp")
	if err != nil {
		return fmt.Errorf("create replacement starter policy: %w", err)
	}
	defer func() { _ = os.Remove(file.Name()) }()

	_, err = file.Write(data)
	if err != nil {
		_ = file.Close()

		return fmt.Errorf("write replacement starter policy: %w", err)
	}

	err = file.Sync()
	if err != nil {
		_ = file.Close()

		return fmt.Errorf("sync replacement starter policy: %w", err)
	}

	err = file.Close()
	if err != nil {
		return fmt.Errorf("close replacement starter policy: %w", err)
	}

	err = root.Rename(filepath.Base(file.Name()), name)
	if err != nil {
		return fmt.Errorf("replace starter policy: %w", err)
	}

	return nil
}
