package cli_test

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/DiLRandI/OTelPlan/internal/cli"
	"github.com/DiLRandI/OTelPlan/internal/policy"
	"github.com/DiLRandI/OTelPlan/internal/suggest"
	"github.com/DiLRandI/OTelPlan/pkg/model"
)

func TestInitWritesDeterministicExactPolicy(t *testing.T) {
	t.Parallel()

	root, directory, original := callGraphFixture(t)
	path := filepath.Join(root, "otelplan.yaml")

	var stdout, stderr bytes.Buffer

	args := []string{"init", "--root", root, "--offline", "--non-interactive", "--format=json"}
	if exit := cli.Run(t.Context(), args, &stdout, &stderr); exit != 0 {
		t.Fatalf("init exit=%d: %s %s", exit, &stdout, &stderr)
	}

	checkInitResponse(t, stdout.Bytes(), path)

	generated, err := directory.ReadFile("otelplan.yaml")
	if err != nil {
		t.Fatal(err)
	}

	checkStarterPolicy(t, path, generated)
	checkInitRewrites(t, directory, args, generated)

	for name, want := range original {
		actual, err := directory.ReadFile(name)
		if err != nil || string(actual) != want {
			t.Fatalf("init changed %s", name)
		}
	}
}

func checkInitResponse(t *testing.T, output []byte, path string) {
	t.Helper()

	var reply struct {
		APIVersion string `json:"apiVersion"`
		Command    string `json:"command"`
		OK         bool   `json:"ok"`
		Data       struct {
			Path        string               `json:"path"`
			Suggestions []suggest.Suggestion `json:"suggestions"`
		} `json:"data"`
	}

	err := json.Unmarshal(output, &reply)
	if err != nil {
		t.Fatal(err)
	}

	if !reply.OK || reply.APIVersion != cli.APIVersion || reply.Command != "init" || reply.Data.Path != path {
		t.Fatalf("invalid init response: %s", output)
	}

	if len(reply.Data.Suggestions) != 2 || reply.Data.Suggestions[0].SymbolID != "example.com/app.Run" {
		t.Fatalf("unexpected suggestions: %+v", reply.Data.Suggestions)
	}
}

func checkInitRewrites(t *testing.T, directory *os.Root, args []string, generated []byte) {
	t.Helper()

	var stdout, stderr bytes.Buffer

	if exit := cli.Run(t.Context(), args, &stdout, &stderr); exit != 1 {
		t.Fatalf("init overwrote policy without --force: exit=%d %s", exit, &stdout)
	}

	unchanged, err := directory.ReadFile("otelplan.yaml")
	if err != nil || !bytes.Equal(unchanged, generated) {
		t.Fatal("rejected init changed policy")
	}

	stdout.Reset()

	if exit := cli.Run(t.Context(), slices.Concat(args, []string{"--force"}), &stdout, &stderr); exit != 0 {
		t.Fatalf("forced init exit=%d: %s %s", exit, &stdout, &stderr)
	}

	repeated, err := directory.ReadFile("otelplan.yaml")
	if err != nil || !bytes.Equal(repeated, generated) {
		t.Fatal("identical analysis changed generated policy")
	}
}

func checkStarterPolicy(t *testing.T, path string, generated []byte) {
	t.Helper()

	if !bytes.HasPrefix(generated, []byte("# Generated by otelplan init.")) {
		t.Fatal("starter policy has no review guidance")
	}

	parsed, err := policy.Load(path)
	if err != nil || policy.Validate(parsed).HasErrors() {
		t.Fatalf("generated policy is invalid: %v", err)
	}

	if parsed.Backend.Version != "v1.1.0" || parsed.Defaults.Context.Mode != model.ContextModeRequire ||
		parsed.Defaults.Attributes.Arguments || parsed.Defaults.Attributes.Results || len(parsed.Rules) != 2 {
		t.Fatalf("unsafe or incomplete starter policy: %+v", parsed)
	}

	checkStarterRules(t, parsed.Rules)
}

func checkStarterRules(t *testing.T, rules []model.Rule) {
	t.Helper()

	for _, rule := range rules {
		if len(rule.Match.Symbols) != 1 || rule.Description == "" || !strings.HasPrefix(rule.ID, "suggest-") {
			t.Fatalf("starter rule is not exact and explained: %+v", rule)
		}
	}
}

func TestInitOutputAndUsageErrors(t *testing.T) {
	t.Parallel()

	root, _, _ := callGraphFixture(t)

	var stdout, stderr bytes.Buffer

	args := []string{"init", "--root", root, "--offline", "--output=starter.yml"}
	if exit := cli.Run(t.Context(), args, &stdout, &stderr); exit != 0 {
		t.Fatalf("custom output exit=%d: %s %s", exit, &stdout, &stderr)
	}

	_, err := os.Stat(filepath.Join(root, "starter.yml"))
	if err != nil {
		t.Fatal(err)
	}

	_, err = os.Stat(filepath.Join(root, "otelplan.yaml"))
	if !os.IsNotExist(err) {
		t.Fatal("custom output also wrote default policy")
	}

	for _, arguments := range [][]string{
		{"scan", "--force"}, {"scan", "--non-interactive"},
		{"scan", "--output=starter.yml"}, {"init", "--root", root, "--output=go.mod"},
	} {
		stdout.Reset()
		stderr.Reset()

		arguments = append(arguments, "--format=json")
		if exit := cli.Run(t.Context(), arguments, &stdout, &stderr); exit != 2 {
			t.Fatalf("invalid usage %v exit=%d: %s %s", arguments, exit, &stdout, &stderr)
		}

		var reply struct {
			OK          bool                      `json:"ok"`
			Diagnostics model.DiagnosticErrorList `json:"diagnostics"`
		}

		err = json.Unmarshal(stdout.Bytes(), &reply)
		if err != nil || reply.OK || len(reply.Diagnostics) == 0 {
			t.Fatalf("invalid JSON usage response: %s (%v)", &stdout, err)
		}
	}
}

func TestInitWithoutSafeCandidatesDoesNotWrite(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	for name, content := range map[string]string{
		"go.mod": "module example.com/no-context\n\ngo 1.27\n",
		"app.go": "package app\nfunc Run() {}\n",
	} {
		err := os.WriteFile(filepath.Join(root, name), []byte(content), 0o600)
		if err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer

	args := []string{"init", "--root", root, "--offline", "--format=json"}
	if exit := cli.Run(t.Context(), args, &stdout, &stderr); exit != 5 {
		t.Fatalf("contextless init exit=%d: %s %s", exit, &stdout, &stderr)
	}

	_, err := os.Stat(filepath.Join(root, "otelplan.yaml"))
	if !os.IsNotExist(err) {
		t.Fatal("init without safe candidates wrote a policy")
	}
}
