package otelc

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/DiLRandI/OTelPlan/pkg/model"
	"golang.org/x/mod/module"
)

type GeneratedFile struct {
	Path string
	Data []byte
}

type BundleManifest struct {
	APIVersion     string               `json:"apiVersion"`
	Backend        model.LockBackend    `json:"backend"`
	RuntimeVersion string               `json:"runtimeVersion"`
	ModulePath     string               `json:"modulePath"`
	Files          []model.ArtifactFile `json:"files"`
}

// RenderBundle renders source artifacts without modifying module state. The
// manifest inventories payload files; callers also hash manifest.json for locks.
func RenderBundle(backend model.LockBackend, runtimeVersion string, code *model.CodeModel, plan model.ResolvedPlan, modulePath string) ([]GeneratedFile, error) {
	identity, err := Identity(backend.Version)
	if err != nil {
		return nil, err
	}
	if backend.Name != identity.Name || backend.Capabilities != identity.Capabilities {
		return nil, fmt.Errorf("backend identity does not match pinned capabilities")
	}
	if backend.Digest != "" {
		digest, err := hex.DecodeString(strings.TrimPrefix(backend.Digest, "sha256:"))
		if err != nil || len(digest) != sha256.Size || backend.Digest != fmt.Sprintf("sha256:%x", digest) {
			return nil, fmt.Errorf("invalid backend executable digest")
		}
	}
	if err := module.CheckPath(modulePath); err != nil {
		return nil, fmt.Errorf("invalid generated module path")
	}
	hooks, err := RenderHooks(backend.Version, runtimeVersion, code, plan, modulePath+"/hooks")
	if err != nil {
		return nil, err
	}
	rules, _, err := RenderRules(backend.Version, code, plan, modulePath+"/hooks")
	if err != nil {
		return nil, err
	}
	accessorRules, helpers, err := RenderAccessorRules(backend.Version, code, plan, modulePath+"/accessors")
	if err != nil {
		return nil, err
	}
	files := []GeneratedFile{{Path: "hooks/hooks.go", Data: hooks}, {Path: "rules/hooks.otelc.yaml", Data: rules}}
	if len(helpers) > 0 {
		files = append(files, GeneratedFile{Path: "rules/accessors.otelc.yaml", Data: accessorRules}, GeneratedFile{Path: "accessors/package.go", Data: []byte("// Code generated by OTelPlan. DO NOT EDIT.\n\npackage accessors\n")})
		for _, helper := range helpers {
			files = append(files, GeneratedFile{Path: "accessors/" + helper.Name, Data: helper.Source})
		}
	}
	moduleFiles, err := renderRuntimeModule(modulePath)
	if err != nil {
		return nil, err
	}
	files = append(files, moduleFiles...)
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	manifest := BundleManifest{APIVersion: "otelplan.io/artifacts/v1alpha1", Backend: backend, RuntimeVersion: runtimeVersion, ModulePath: modulePath, Files: make([]model.ArtifactFile, 0, len(files))}
	for _, file := range files {
		manifest.Files = append(manifest.Files, model.ArtifactFile{Path: file.Path, Digest: fmt.Sprintf("sha256:%x", sha256.Sum256(file.Data))})
	}
	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode artifact manifest: %w", err)
	}
	files = append(files, GeneratedFile{Path: "manifest.json", Data: append(data, '\n')})
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}
