package otelc

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/DiLRandI/OTelPlan/pkg/model"
	"golang.org/x/mod/module"
)

var (
	errBundleBackendCapabilities = errors.New("backend identity does not match pinned capabilities")
	errBundleBackendDigest       = errors.New("invalid backend executable digest")
	errBundleModulePath          = errors.New("invalid generated module path")
)

// GeneratedFile pairs a bundle-relative path with rendered bytes.
type GeneratedFile struct {
	Path string
	Data []byte
}

// BundleManifest inventories payload identities and pinned backend/runtime metadata.
type BundleManifest struct {
	APIVersion     string               `json:"apiVersion"`
	Backend        model.LockBackend    `json:"backend"`
	RuntimeVersion string               `json:"runtimeVersion"`
	ModulePath     string               `json:"modulePath"`
	Files          []model.ArtifactFile `json:"files"`
}

// RenderBundle renders source artifacts without modifying module state. The
// manifest inventories payload files; callers also hash manifest.json for locks.
func RenderBundle(backend model.LockBackend, runtimeVersion string, code *model.CodeModel,
	plan model.ResolvedPlan, modulePath string) ([]GeneratedFile, error) {
	err := validateBundleBackend(backend)
	if err != nil {
		return nil, err
	}

	err = module.CheckPath(modulePath)
	if err != nil {
		return nil, errBundleModulePath
	}

	files, err := renderBundlePayload(backend, runtimeVersion, code, plan, modulePath)
	if err != nil {
		return nil, err
	}

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	manifest, err := bundleManifestFile(backend, runtimeVersion, modulePath, files)
	if err != nil {
		return nil, err
	}

	files = append(files, manifest)
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	return files, nil
}

func validateBundleBackend(backend model.LockBackend) error {
	identity, err := Identity(backend.Version)
	if err != nil {
		return err
	}

	if backend.Name != identity.Name || backend.Capabilities != identity.Capabilities {
		return errBundleBackendCapabilities
	}

	if backend.Digest == "" {
		return nil
	}

	digest, err := hex.DecodeString(strings.TrimPrefix(backend.Digest, "sha256:"))
	if err != nil || len(digest) != sha256.Size || backend.Digest != fmt.Sprintf("sha256:%x", digest) {
		return errBundleBackendDigest
	}

	return nil
}

func renderBundlePayload(backend model.LockBackend, runtimeVersion string, code *model.CodeModel,
	plan model.ResolvedPlan, modulePath string) ([]GeneratedFile, error) {
	hooks, err := RenderHooks(backend.Version, runtimeVersion, code, plan, modulePath+"/hooks")
	if err != nil {
		return nil, err
	}

	rules, _, err := RenderRules(backend.Version, code, plan, modulePath+"/hooks")
	if err != nil {
		return nil, err
	}

	accessorRules, helpers, err := RenderAccessorRules(backend.Version, code, plan, modulePath+"/accessors")
	if err != nil {
		return nil, err
	}

	files := []GeneratedFile{{Path: "hooks/hooks.go", Data: hooks}, {Path: "rules/hooks.otelc.yaml", Data: rules}}

	if len(helpers) > 0 {
		packageSource := []byte("// Code generated by OTelPlan. DO NOT EDIT.\n\npackage accessors\n")
		files = append(files, GeneratedFile{Path: "rules/accessors.otelc.yaml", Data: accessorRules},
			GeneratedFile{Path: "accessors/package.go", Data: packageSource})

		for _, helper := range helpers {
			files = append(files, GeneratedFile{Path: "accessors/" + helper.Name, Data: helper.Source})
		}
	}

	moduleFiles, err := renderRuntimeModule(modulePath)
	if err != nil {
		return nil, err
	}

	return append(files, moduleFiles...), nil
}

func bundleManifestFile(backend model.LockBackend, runtimeVersion, modulePath string,
	files []GeneratedFile) (GeneratedFile, error) {
	var empty GeneratedFile

	manifest := BundleManifest{
		APIVersion: "otelplan.io/artifacts/v1alpha1", Backend: backend, RuntimeVersion: runtimeVersion,
		ModulePath: modulePath, Files: make([]model.ArtifactFile, 0, len(files)),
	}
	for _, file := range files {
		manifest.Files = append(manifest.Files, model.ArtifactFile{
			Path: file.Path, Digest: fmt.Sprintf("sha256:%x", sha256.Sum256(file.Data)),
		})
	}

	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return empty, fmt.Errorf("encode artifact manifest: %w", err)
	}

	return GeneratedFile{Path: "manifest.json", Data: append(data, '\n')}, nil
}
