package otelc

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/DiLRandI/OTelPlan/pkg/model"
)

// RenderHooks generates lifecycle hooks for the exact bindings from RenderRules.
// It returns source bytes only; writing artifacts and building are separate phases.
func RenderHooks(version, runtimeVersion string, code *model.CodeModel, plan model.ResolvedPlan, hookImportPath string) ([]byte, error) {
	if strings.TrimSpace(runtimeVersion) == "" {
		return nil, fmt.Errorf("hook generation requires an instrumentation version")
	}
	_, bindings, err := RenderRules(version, code, plan, hookImportPath)
	if err != nil {
		return nil, err
	}
	if len(bindings) == 0 {
		return []byte("// Code generated by OTelPlan. DO NOT EDIT.\n\npackage hooks\n"), nil
	}
	targets := make(map[model.SymbolID]model.ResolvedTarget, len(plan.Targets))
	recordErrors := false
	for _, target := range plan.Targets {
		symbol, _ := code.Symbol(target.SymbolID)
		if strings.TrimSpace(target.SpanName) == "" {
			return nil, fmt.Errorf("hook generation requires a span name")
		}
		if len(target.Attributes) != 0 {
			return nil, fmt.Errorf("attribute hooks require typed accessor generation")
		}
		if symbol.Variadic {
			return nil, fmt.Errorf("variadic hooks require typed signature generation")
		}
		seen := make(map[int]bool, len(target.ErrorStrategy.Indexes))
		for _, index := range target.ErrorStrategy.Indexes {
			if seen[index] {
				return nil, fmt.Errorf("hook error result indexes must be unique")
			}
			seen[index] = true
			recordErrors = true
		}
		targets[target.SymbolID] = target
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by OTelPlan. DO NOT EDIT.\n\npackage hooks\n\nimport (\n\"context\"\n\"go.opentelemetry.io/otel\"\n\"go.opentelemetry.io/otel/trace\"\n\"go.opentelemetry.io/otelc/pkg/hook\"\n")
	if recordErrors {
		source.WriteString("\"go.opentelemetry.io/otel/codes\"\n")
	}
	source.WriteString(")\n")
	for _, binding := range bindings {
		target := targets[binding.Symbol]
		symbol, _ := code.Symbol(binding.Symbol)
		parameters := len(symbol.Parameters)
		offset := 0
		if symbol.Receiver != nil {
			parameters++
			offset = 1
		}
		fmt.Fprintf(&source, "\nfunc %s(h hook.HookContext%s) {\n", binding.Before, strings.Repeat(", _ any", parameters))
		if target.ContextStrategy.Strategy == model.ContextStrategyArgument {
			fmt.Fprintf(&source, "ctx, _ := h.GetParam(%d).(context.Context)\nif ctx == nil { ctx = context.Background() }\n", target.ContextStrategy.Index+offset)
		} else {
			source.WriteString("ctx := context.Background()\n")
		}
		child := "_"
		if target.ContextStrategy.Strategy == model.ContextStrategyArgument {
			child = "child"
		}
		fmt.Fprintf(&source, "%s, span := otel.Tracer(\"otelplan.io/business\", trace.WithInstrumentationVersion(%q)).Start(ctx, %q, trace.WithSpanKind(trace.SpanKindInternal))\nh.SetData(span)\n", child, runtimeVersion, target.SpanName)
		if target.ContextStrategy.Strategy == model.ContextStrategyArgument {
			fmt.Fprintf(&source, "h.SetParam(%d, child)\n", target.ContextStrategy.Index+offset)
		}
		source.WriteString("}\n")
		fmt.Fprintf(&source, "\nfunc %s(h hook.HookContext%s) {\nspan, ok := h.GetData().(trace.Span)\nif !ok { return }\ndefer span.End()\nh.SetData(nil)\n", binding.After, strings.Repeat(", _ any", len(symbol.Results)))
		for _, index := range target.ErrorStrategy.Indexes {
			fmt.Fprintf(&source, "if err, ok := h.GetReturnVal(%d).(error); ok && err != nil {\nspan.RecordError(err)\nspan.SetStatus(codes.Error, \"operation failed\")\n}\n", index)
		}
		source.WriteString("}\n")
	}
	data, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated hooks: %w", err)
	}
	return data, nil
}
