package otelc

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/DiLRandI/OTelPlan/pkg/model"
)

var errUnsupportedVariadicHookElement = errors.New("variadic target has no supported hook element type")

// RenderHooks generates lifecycle hooks for the exact bindings from RenderRules.
// It returns source bytes only; writing artifacts and building are separate phases.
func RenderHooks(version, runtimeVersion string, code *model.CodeModel, plan model.ResolvedPlan, hookImportPath string) ([]byte, error) {
	if strings.TrimSpace(runtimeVersion) == "" {
		return nil, errors.New("hook generation requires an instrumentation version")
	}

	_, bindings, err := RenderRules(version, code, plan, hookImportPath)
	if err != nil {
		return nil, err
	}

	if len(bindings) == 0 {
		return []byte("// Code generated by OTelPlan. DO NOT EDIT.\n\npackage hooks\n"), nil
	}

	targets := make(map[model.SymbolID]model.ResolvedTarget, len(plan.Targets))
	recordErrors := false
	accessors := map[model.SymbolID][]AccessorBinding{}

	for _, target := range plan.Targets {
		if strings.TrimSpace(target.SpanName) == "" {
			return nil, errors.New("hook generation requires a span name")
		}

		if len(target.Attributes) != 0 {
			_, attributes, err := RenderAccessors(code, target)
			if err != nil {
				return nil, err
			}

			accessors[target.SymbolID] = attributes
		}

		seen := make(map[int]bool, len(target.ErrorStrategy.Indexes))
		for _, index := range target.ErrorStrategy.Indexes {
			if seen[index] {
				return nil, errors.New("hook error result indexes must be unique")
			}

			seen[index] = true
			recordErrors = true
		}

		targets[target.SymbolID] = target
	}

	var source bytes.Buffer

	source.WriteString("// Code generated by OTelPlan. DO NOT EDIT.\n\npackage hooks\n\nimport (\n\"context\"\n\"go.opentelemetry.io/otel\"\n\"go.opentelemetry.io/otel/trace\"\n\"go.opentelemetry.io/otelc/pkg/hook\"\n")

	if recordErrors {
		source.WriteString("\"go.opentelemetry.io/otel/codes\"\n")
	}

	if len(accessors) > 0 {
		source.WriteString("\"go.opentelemetry.io/otel/attribute\"\n_ \"unsafe\"\n")
	}

	source.WriteString(")\n")

	for _, binding := range bindings {
		target := targets[binding.Symbol]
		symbol, _ := code.Symbol(binding.Symbol)
		offset := 0

		if symbol.Receiver != nil {
			offset = 1
		}

		beforeParameters, err := beforeHookParameters(symbol, accessors[binding.Symbol])
		if err != nil {
			return nil, err
		}

		for _, accessor := range accessors[binding.Symbol] {
			resultType, _ := scalarType(accessor.Kind)
			fmt.Fprintf(&source, "\n//go:linkname read_%s %s.%s\nfunc read_%s(any) (%s, bool)\n", accessor.Function, symbol.PackageImportPath, accessor.Function, accessor.Function, resultType)
		}

		fmt.Fprintf(&source, "\nfunc %s(h hook.HookContext%s) {\n", binding.Before, beforeParameters)

		if target.ContextStrategy.Strategy == model.ContextStrategyArgument {
			fmt.Fprintf(&source, "ctx, _ := h.GetParam(%d).(context.Context)\nif ctx == nil { ctx = context.Background() }\n", target.ContextStrategy.Index+offset)
		} else {
			source.WriteString("ctx := context.Background()\n")
		}

		child := "_"
		if target.ContextStrategy.Strategy == model.ContextStrategyArgument {
			child = "child"
		}

		fmt.Fprintf(&source, "%s, span := otel.Tracer(\"otelplan.io/business\", trace.WithInstrumentationVersion(%q)).Start(ctx, %q, trace.WithSpanKind(trace.SpanKindInternal))\nh.SetData(span)\n", child, runtimeVersion, target.SpanName)

		if target.ContextStrategy.Strategy == model.ContextStrategyArgument {
			fmt.Fprintf(&source, "h.SetParam(%d, child)\n", target.ContextStrategy.Index+offset)
		}

		writeHookAttributes(&source, symbol, accessors[binding.Symbol], false)
		source.WriteString("}\n")
		fmt.Fprintf(&source, "\nfunc %s(h hook.HookContext%s) {\n"+
			"span, ok := h.GetData().(trace.Span)\nif !ok { return }\ndefer span.End()\nh.SetData(nil)\n",
			binding.After, afterHookParameters(symbol, target.ErrorStrategy.Indexes, accessors[binding.Symbol]))
		writeHookErrors(&source, symbol, target.ErrorStrategy.Indexes)

		writeHookAttributes(&source, symbol, accessors[binding.Symbol], true)
		source.WriteString("}\n")
	}

	data, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated hooks: %w", err)
	}

	return data, nil
}

func beforeHookParameters(symbol *model.Symbol, bindings []AccessorBinding) (string, error) {
	parameters := make([]string, len(symbol.Parameters))
	for index := range symbol.Parameters {
		name, typ := "_", "any"
		if hasTypeParameters(symbol) && hasAccessorInput(bindings, accessorArgumentSource, index) {
			name = fmt.Sprintf("argument_%d", index)
		}

		if symbol.Variadic && index == len(symbol.Parameters)-1 {
			element, supported := variadicElementType(symbol)
			if !supported {
				return "", errUnsupportedVariadicHookElement
			}

			typ = "..." + element
		}

		parameters[index] = fmt.Sprintf(", %s %s", name, typ)
	}

	result := strings.Join(parameters, "")
	if symbol.Receiver != nil {
		result = ", _ any" + result
	}

	return result, nil
}

func hasAccessorInput(bindings []AccessorBinding, source string, index int) bool {
	for _, binding := range bindings {
		if binding.Source == source && binding.Index == index {
			return true
		}
	}

	return false
}

func afterHookParameters(symbol *model.Symbol, errorIndexes []int, bindings []AccessorBinding) string {
	if !hasTypeParameters(symbol) {
		return strings.Repeat(", _ any", len(symbol.Results))
	}

	parameters := make([]string, len(symbol.Results))
	for index := range symbol.Results {
		parameters[index] = ", _ any"
		if slices.Contains(errorIndexes, index) || hasAccessorInput(bindings, accessorResultSource, index) {
			parameters[index] = fmt.Sprintf(", returned_%d any", index)
		}
	}

	return strings.Join(parameters, "")
}

func writeHookErrors(source *bytes.Buffer, symbol *model.Symbol, indexes []int) {
	for _, index := range indexes {
		value := fmt.Sprintf("h.GetReturnVal(%d)", index)
		if hasTypeParameters(symbol) {
			// The pinned backend disables generic result APIs but passes original results directly to after hooks.
			value = fmt.Sprintf("returned_%d", index)
		}

		fmt.Fprintf(source, "if err, ok := %s.(error); ok && err != nil {\nspan.RecordError(err)\n"+
			"span.SetStatus(codes.Error, \"operation failed\")\n}\n", value)
	}
}

func writeHookAttributes(source *bytes.Buffer, symbol *model.Symbol, bindings []AccessorBinding, results bool) {
	opened := false

	for _, binding := range bindings {
		if (binding.Source == accessorResultSource) != results {
			continue
		}

		if !opened {
			source.WriteString("if span.IsRecording() {\n")

			opened = true
		}

		input := hookAttributeInput(symbol, binding)

		constructor := map[string]string{"string": "String", "bool": "Bool", "integer": "Int64", "float": "Float64"}[binding.Kind]
		fmt.Fprintf(source, "if value, ok := read_%s(%s); ok { span.SetAttributes(attribute.%s(%q, value)) }\n", binding.Function, input, constructor, binding.Key)
	}

	if opened {
		source.WriteString("}\n")
	}
}

func hookAttributeInput(symbol *model.Symbol, binding AccessorBinding) string {
	switch binding.Source {
	case accessorArgumentSource:
		if hasTypeParameters(symbol) {
			return fmt.Sprintf("argument_%d", binding.Index)
		}

		offset := 0
		if symbol.Receiver != nil {
			offset = 1
		}

		return fmt.Sprintf("h.GetParam(%d)", binding.Index+offset)
	case accessorResultSource:
		if hasTypeParameters(symbol) {
			return fmt.Sprintf("returned_%d", binding.Index)
		}

		return fmt.Sprintf("h.GetReturnVal(%d)", binding.Index)
	default:
		return "nil"
	}
}
